#端口号，根目录
server:
  port: 8081
  servlet:
    context-path: /prod/shiro

#热部署
spring:
  devtools:
    restart:
      enabled: true

#jsp视图支持
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:cn/xuyue/shirowithspringboot/mapper/*.xml
  type-aliases-package: cn.xuyue.shirowithspringboot.pojo